rootProject.name = 'Spring-Hibernate'

include 'bean-lifecycle'
include 'spring-events'
include 'byte-manipulation'
include 'byte-buddy'
include 'byte-buddy-agent'
include 'converter'
include 'jms'
include 'webflux'
include 'proxy'
include 'csv-converter'
include 'file-integration'
include 'task-validator'
include 'library'
include 'security-common'