spring.profiles.active=simple

app.paths.reverse-input=file-integration/data/reverse/input
app.paths.reverse-output=file-integration/data/reverse/output

app.paths.monitor-observed=file-integration/data/monitor/observed
app.paths.monitor-result=file-integration/data/monitor/result
app.paths.monitor-result-simple=file-integration/data/monitor/result/simple